name: Node.js CI

on:
  push:
    branches: [main, alpha]
  pull_request:
    branches: [main, alpha]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn --frozen-lockfile

      - name: 'Build'
        run: yarn build

      - name: 'Release'
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
